language: objective-c
xcode_project: Tor.xcodeproj
script:
  - xcodebuild $XCODE_ACTION -project "$TRAVIS_XCODE_PROJECT" -scheme "$TRAVIS_XCODE_SCHEME" -sdk "$TRAVIS_XCODE_SDK" -destination "$XCODE_DESTINATION"
matrix:
  include:
    - xcode_scheme: "Tor-iOS"
      xcode_sdk: iphoneos
      osx_image: xcode8
      env:
        - XCODE_ACTION=build
        - XCODE_DESTINATION="generic/platform=iOS"
    - xcode_scheme: "Tor-iOS"
      xcode_sdk: iphoneos
      osx_image: xcode9
      env:
        - XCODE_ACTION=build
        - XCODE_DESTINATION="generic/platform=iOS"
